### PR TITLE
Implements github CI

### PR DESCRIPTION
**Pull request by Kreyren**
**MAINTAINERS:** This is a followup on https://github.com/PistonDevelopers/piston-examples/pull/466

This runs build of specific example when it is proposed for merge or
pushed to the repository, runs on stable, beta, nightly and specified
version in this implemenetaion it's 1.44.0

Signed-off-by: Jacob Hrbek <kreyren@fsfe.org>

### CODE REVIEW

**Comment by Kreyren** [comment]
Credit: Cargo-make <https://github.com/sagiegurari/cargo-make>

**Comment by Kreyren** [comment]
See it in action on https://github.com/Kreyren/piston-examples/pull/1

**Comment by Kreyren** [comment]
CC @bvssvni

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
