### PR TITLE
Use cargo examples

### PR DESCRIPTION
**Pull request by Kreyren**
This makes use of the `examples` directory that to me makes the
repository more readable as it differentiates cleary what are examples
from other repository pathnames

Tested all examples using method provided in `README.md` and did not
notice any issues, but the result should be peer-reviewed

Signed-off-by: Jacob Hrbek <kreyren@fsfe.org>

### CODE REVIEW

**Comment by Kreyren** [comment]
Do-not-merge: rebased to wrong branch

**Comment by bvssvni** [comment]
@Kreyren can you rebase?

**Comment by Kreyren** [comment]
@bvssvni review

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Comment by Kreyren** [comment]
FWIW i suggest merging this repository in https://github.com/PistonDevelopers/piston for more efficient maintenance.

**Comment by bvssvni** [comment]
@Kreyren that's a good idea! The problem is that when changing the Piston version, one has to update the entire ecosystem before getting the examples to compile.

**Comment by Kreyren** [comment]
> @Kreyren that's a good idea! The problem is that when changing the Piston version, one has to update the entire ecosystem before getting the examples to compile.

I see i guess we could use `cargo-eval` syntax (afaik used by cargo when called the example command) to hardcode the dependencies for the example to run on known working version and tracking the issue.

example from https://github.com/reitermarkus/cargo-eval#templates

```rs
//! This is a regular crate doc comment, but it also contains a partial
//! Cargo manifest.  Note the use of a *fenced* code block, and the
//! `cargo` "language".
//!
//! ```cargo
//! [dependencies]
//! time = "0.1.25"
//! ```
extern crate time;
fn main() {
    println!("{}", time::now().rfc822z());
}
```

Or why is this issue related to examples?

FWIW on first sight it seems like something release control would handle?

**Comment by bvssvni** [comment]
@Kreyren Hmm... that seems a little complicated. 😟 For now, I think it's fine to have to two separate repositories.

I think the reason this is related to examples, is because you depend on the library and dev-dependencies, so Cargo tries to link two versions of the same library.

**Pull request merged**
